version: '3.4'

services:
    catalogdb:
        container_name: catalogdb
        restart: always
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
        ports:
            - "27017:27017"

    basketdb:
        container_name: basketdb
        restart: always
        ports:
            - "6379:6379"

    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"

    orderdb:
        container_name: orderdb
        restart: always
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "P@ssw0rd"
            ACCEPT_EULA: "Y"

    catalog.api:
        container_name: catalog-api
        hostname: catalog.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
        depends_on:
            - catalogdb
        volumes:
            - ${HOME}/.microsoft/usersecrests/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https/:/root/.aspnet/https/
        ports:
            - "8000:80"

    basket.api:
        container_name: basket-api
        hostname: basket.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:Redis=basketdb:6379"
            - "EventBus:HostName=rabbitmq"
        depends_on:
            - basketdb
            - rabbitmq
        volumes:
            - ${HOME}/.microsoft/usersecrests/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https/:/root/.aspnet/https/
        ports:
            - "8001:80"


    orders.api:
        container_name: orders-api
        hostname: orders.api
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__OrderConnection=server=orderdb,1433; Database=OrderDb; User Id=sa; Password=P@ssw0rd
            - "EventBus:HostName=rabbitmq"
        ports:
            - "8002:80"
        volumes:
            - ${HOME}/.microsoft/usersecrests/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https/:/root/.aspnet/https/
        depends_on:
            - orderdb
            - rabbitmq

    apigateway:
        container_name: apigateway
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - catalog.api
            - basket.api
            - orders.api
        volumes:
            - ${HOME}/.microsoft/usersecrests/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https/:/root/.aspnet/https/
        ports:
            - "7000:80"